pipeline {
    agent any

    environment {
        // Adjust this path if vcpkg is installed somewhere else
        VCPKG_ROOT = "/home/sam/vcpkg"
        // Build folder name
        BUILD_DIR = "build"
    }

    stages {
        stage('Install Dependencies') {
            steps {
                // 1. Move into the source folder where vcpkg.json is located
                dir('MathGameMain') {
                    script {
                        // This uses the vcpkg.json file in this folder
                        sh '${VCPKG_ROOT}/vcpkg install'
                    }
                }
            }
        }

        stage('Configure') {
            steps {
                // 2. Move into the source folder where CMakeLists.txt is located
                dir('MathGameMain') {
                    script {
                        // -S . tells CMake to look in the current directory (MathGameMain)
                        sh """
                            cmake -B ${BUILD_DIR} -S . \
                            -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake \
                            -DCMAKE_BUILD_TYPE=Debug \
                            -DENABLE_COVERAGE=ON
                        """
                    }
                }
            }
        }

        stage('Build') {
            steps {
                dir('MathGameMain') {
                    script {
                        sh "cmake --build ${BUILD_DIR}"
                    }
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('MathGameMain') {
                    // 3. Run the tests from inside the build directory
                    dir("${BUILD_DIR}") {
                        script {
                            sh './RunTests -r junit -o results.xml'
                        }
                    }
                }
            }
            post {
                always {
                    // Publish the JUnit test results
                    junit "MathGameMain/${BUILD_DIR}/results.xml"
                }
            }
        }

        stage('Run Game (Verify)') {
            steps {
                dir('MathGameMain') {
                    dir("${BUILD_DIR}") {
                        script {
                            // Start server in background, verify it, and kill it
                            sh 'nohup ./MathGame > server.log 2>&1 & echo $! > pid.file'
                            sleep 5
                            sh 'curl -v --fail http://localhost:18080/'
                            sh 'kill $(cat pid.file)'
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}