pipeline {
    agent any

    environment {
        // Based on your logs, vcpkg is at /home/sam/vcpkg
        VCPKG_ROOT = "/home/sam/vcpkg"
        // We will create the build folder INSIDE the MathGameMain folder
        BUILD_DIR = "build"
    }

    stages {
        stage('Install Dependencies') {
            steps {
                // 1. Enter the project folder
                dir('MathGameMain') {
                    script {
                        // Run vcpkg install here so it finds vcpkg.json
                        sh '${VCPKG_ROOT}/vcpkg install'
                    }
                }
            }
        }

        stage('Configure') {
            steps {
                dir('MathGameMain') {
                    // 2. Configure CMake inside the folder
                    // -S . means "source is in current folder" (which is now MathGameMain)
                    sh """
                        cmake -B ${BUILD_DIR} -S . \
                        -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake \
                        -DCMAKE_BUILD_TYPE=Debug \
                        -DENABLE_COVERAGE=ON
                    """
                }
            }
        }

        stage('Build') {
            steps {
                dir('MathGameMain') {
                    // 3. Build inside the folder
                    sh "cmake --build ${BUILD_DIR}"
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('MathGameMain') {
                    dir("${BUILD_DIR}") {
                        // 4. Run tests inside the build folder
                        sh './RunTests -r junit -o results.xml'
                    }
                }
            }
            post {
                always {
                    // Jenkins looks for the results file relative to workspace root
                    junit "MathGameMain/${BUILD_DIR}/results.xml"
                }
            }
        }

        stage('Run Game (Verify)') {
            steps {
                dir('MathGameMain') {
                    dir("${BUILD_DIR}") {
                        // 5. Dry run verification
                        sh 'nohup ./MathGame > server.log 2>&1 & echo $! > pid.file'
                        sleep 5
                        sh 'curl -v --fail http://localhost:18080/'
                        sh 'kill $(cat pid.file)'
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}